version: "3.9"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  chat_backend:
    build: ./chat_backend
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    volumes:
      - ./chat_backend:/app

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - chat_backend
    volumes:
      - ./frontend:/app
    command: npm start

volumes:
  ollama_data:
